services:
  traefik:
    image: traefik:v3.3
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@msolsys.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_acme:/letsencrypt"
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


networks:
  traefik:
    name: traefik
    driver: overlay
    attachable: true

volumes:
  traefik_acme:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /traefik/acme_volume/