services:
  whoami:
    image: python:3.13
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.whoami.rule=Host(`test.msolsys.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik
    volumes:
      - "./index.html:/usr/share/nginx/html/index.html"
    command: bash -c "echo '<h1>Hello, World!</h1>' > /usr/share/nginx/html/index.html && python -m http.server 80"
    working_dir: /usr/share/nginx/html


networks:
  traefik:
    name: traefik
    external: true